
services:
  postgres:
    image: postgis/postgis:latest
    platform: linux/amd64
    container_name: postgis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
