version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.pgsql
    image: srer/db
    env_file: .env
    volumes:
      - .docker/pgsql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: srer/app
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - .:/opt/app
    stdin_open: true
    tty: true
    links:
      - db
    depends_on:
      - db
    command: /bin/bash
