# Generated by Django 2.1.2 on 2018-10-07 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecipEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('precip', models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True)),
            ],
            options={
                'verbose_name': 'Precip Events',
                'verbose_name_plural': 'Precip Events',
            },
        ),
        migrations.CreateModel(
            name='Raingage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=125, null=True)),
                ('name', models.CharField(blank=True, max_length=125, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Raingage',
                'verbose_name_plural': 'Raingages',
            },
        ),
        migrations.AddField(
            model_name='precipevent',
            name='raingage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precip.Raingage'),
        ),
    ]
